### ISSUE TITLE
ModuleNotFoundError: No module named 'src.dataset'

### ISSUE THREAD

**Issue by rystylee** [novitalabs/AnimateAnyone#3]
In pipeline_pose2vid_long.py, trying to load a module called src.dataset.utils but the source code doesn't exist.
Did you forget to upload it?

The following is the full text of the executed command and the error output.
```
python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 784 -L 64
/home/ryosuke/.pyenv/versions/animate-anyone/lib/python3.10/site-packages/diffusers/models/dual_transformer_2d.py:20: FutureWarning: `DualTransformer2DModel` is deprecated and will be removed in version 0.29. Importing `DualTransformer2DModel` from `diffusers.models.dual_transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel`, instead.
  deprecate("DualTransformer2DModel", "0.29", deprecation_message)
Traceback (most recent call last):
  File "/home/ryosuke/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ryosuke/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/NAS/users/ryosuke/projects/dance/AnimateAnyone/scripts/pose2vid.py", line 23, in <module>
    from src.pipelines.pipeline_pose2vid_long import Pose2VideoPipeline
  File "/media/NAS/users/ryosuke/projects/dance/AnimateAnyone/src/pipelines/pipeline_pose2vid_long.py", line 28, in <module>
    from ..dataset.utils import SquarePad
ModuleNotFoundError: No module named 'src.dataset'
```

**Comment by zhanghongyong123456** [comment]
> In pipeline_pose2vid_long.py, trying to load a module called src.dataset.utils but the source code doesn't exist. Did you forget to upload it?
> 
> The following is the full text of the executed command and the error output.
> 
> ```
> python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 784 -L 64
> /home/ryosuke/.pyenv/versions/animate-anyone/lib/python3.10/site-packages/diffusers/models/dual_transformer_2d.py:20: FutureWarning: `DualTransformer2DModel` is deprecated and will be removed in version 0.29. Importing `DualTransformer2DModel` from `diffusers.models.dual_transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel`, instead.
>   deprecate("DualTransformer2DModel", "0.29", deprecation_message)
> Traceback (most recent call last):
>   File "/home/ryosuke/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/ryosuke/.pyenv/versions/3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/media/NAS/users/ryosuke/projects/dance/AnimateAnyone/scripts/pose2vid.py", line 23, in <module>
>     from src.pipelines.pipeline_pose2vid_long import Pose2VideoPipeline
>   File "/media/NAS/users/ryosuke/projects/dance/AnimateAnyone/src/pipelines/pipeline_pose2vid_long.py", line 28, in <module>
>     from ..dataset.utils import SquarePad
> ModuleNotFoundError: No module named 'src.dataset'
> ```

I  not  find  ModuleNotFoundError: No module named 'configs.prompts.test_cases'  and  No module named 'src.dataset'  
i  copy   Moore-AnimateAnyone  project files but   have new  error，No module named 'src.dataset.utils'

**Comment by k-l-lambda** [comment]
Thanks. It's fixed: [commit: fixed SquarePad missing](https://github.com/novitalabs/AnimateAnyone/commit/a4aa09568756334bae62a5dd61ffc0c2d8ef5b88)

**Comment by zhanghongyong123456** [comment]
> Thanks. It's fixed: [commit: fixed SquarePad missing](https://github.com/novitalabs/AnimateAnyone/commit/a4aa09568756334bae62a5dd61ffc0c2d8ef5b88)

about  AnimateAnyone\src\pipelines\utils.py   to_numpy_array  and  F  not  define （line 46） ，I fix  
![image](https://github.com/novitalabs/AnimateAnyone/assets/48466610/5a6169e1-b8eb-4b43-8135-593b66b6e83d)
![image](https://github.com/novitalabs/AnimateAnyone/assets/48466610/9316299d-1b7d-469b-b7d1-a3087bd813d5)
but  have new error:
![image](https://github.com/novitalabs/AnimateAnyone/assets/48466610/e375ed5b-a887-452d-a05c-3a0032cb9ad6)
so  I think  to_numpy_array Function, not just a simple PIL2Numpy array,Expect to provide this function

**Comment by k-l-lambda** [comment]
@zhanghongyong123456 that's fixed too. Please pull to latest.

`from transformers.image_utils import to_numpy_array`

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456 that's fixed too. Please pull to latest.
> 
> `from transformers.image_utils import to_numpy_array`

It's  OK ,

**Comment by zhanghongyong123456** [comment]
我想请教大佬一下关于openpose 姿态一个问题： 我DWPose：当我禁用人脸检测得到简易姿态，那我如何得到简易的手指姿态呢
![image](https://github.com/novitalabs/AnimateAnyone/assets/48466610/7c05a488-12f7-4c93-9557-545aaf408a68)

**Comment by k-l-lambda** [comment]
@zhanghongyong123456 Sorry, you can't. See [here](https://github.com/novitalabs/AnimateAnyone/blob/main/src/dwpose/util.py#L213).
